version: "3.8"

services:
  credit-risk-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  # optional if using MLflow separately

